apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "go-slack-poll.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-slack-poll.name" . }}
    helm.sh/chart: {{ include "go-slack-poll.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go-slack-poll.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "go-slack-poll.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "SLACK_SIGNING_SECRET"
              valueFrom:
                secretKeyRef:
                  key: slackSigningSecret
                  name: {{ .Release.Name }}-auth
            - name: "REDIS_HOST"
              value: {{ .Release.Name }}-redis-master
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: {{ .Release.Name }}-redis
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
